  # This is a basic workflow to help you get started with Actions

name: gitkhoj

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      queries:
        required: true
        type: string
        default: keyword1,keyword2,keyword3
        description: 'comma separated search keywords e.g. for searching keyword1, keyword2 and keyword3 separately in all orgs input keyword1,keyword2,keyword3'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  searching:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: run script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python main.py -t "$GH_TOKEN" -q "${{ inputs.queries }}"
        shell: sh
        
      - name: uploading the output file
        uses: actions/upload-artifact@v4
        with:
          name: output-download
          path: github-scan.csv
